name: VLA-0
channels:
  - pytorch
  - nvidia/label/cuda-12.4.0
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - cudatoolkit
  - numpy
  - pillow
  - pip
  - tqdm
  - pyyaml
  - matplotlib
  - pandas
  - cython
  - accelerate
  - git
  - cmake
  - ninja
  - openmpi  # 一般没用到，但在某些torch.distributed后端下会有依赖；保留没坏处
  - pip:
      - transformers>=4.43.0
      - qwen-vl-utils
      - opencv-python
      - einops
      - sentencepiece
      - safetensors
      - datasets
      - huggingface_hub
      - gymnasium
      - mujoco
      - imageio
      - imageio-ffmpeg
      - pyquaternion
