name: vla0-env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1
  - torchvision=0.16
  - pip
  - pip:
      - transformers==4.35.2
      - accelerate==0.24.1
      - qwen-vl-utils==0.0.8
      - datasets==2.14.6
      - opencv-python==4.8.1.78
      - numpy==1.24.3
      - h5py
      - gym==0.26.2
      - libero==0.2.0
      - matplotlib
